# Generated by Django 3.0.1 on 2019-12-23 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('limit', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('create_day', models.DateField()),
                ('end_day', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Dormant'), ('0', 'Inactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('atm_balance', models.BigIntegerField()),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Deactive')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bank_name', models.TextField()),
                ('bank_headquarters', models.TextField()),
                ('bank_phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.TextField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_no', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=6)),
                ('create_date', models.DateField()),
                ('end_date', models.DateField()),
                ('card_type', models.CharField(choices=[('1', 'Thẻ tín dụng'), ('2', 'Thẻ ATM'), ('3', 'Thẻ ghi nợ'), ('4', 'Thẻ đảm bảo'), ('5', 'Thẻ Visa')], max_length=1)),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Deactive')], max_length=1)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('province_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RT', 'withdrawal'), ('CKC', 'internal transfer'), ('CKK', 'interbank transfer')], max_length=3)),
                ('transaction_time', models.DateTimeField()),
                ('balance', models.BigIntegerField()),
                ('transaction_fee', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'success'), ('0', 'fail')], max_length=1)),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.ATM')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Bank')),
                ('card_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Card')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMoney',
            fields=[
                ('history_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('history_time', models.DateTimeField()),
                ('money', models.BigIntegerField()),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=32)),
                ('emp_password', models.CharField(max_length=50)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=32)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
                ('hometown', models.TextField()),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('card_type', models.CharField(choices=[('CMND', 'Chứng minh nhân dân'), ('TCC', 'Thẻ căn cước'), ('HC', 'Hộ chiếu')], max_length=4)),
                ('card_no', models.CharField(max_length=15, unique=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Province'),
        ),
        migrations.AddField(
            model_name='bank',
            name='branches',
            field=models.ManyToManyField(through='Hoang.Branch', to='Hoang.Province'),
        ),
        migrations.AddField(
            model_name='atm',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Employee'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hoang.Customer'),
        ),
    ]
