# Generated by Django 3.0.1 on 2019-12-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Long', '0001_initial'),
        ('Hoang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='province_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='historymoney',
            name='atm_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.Branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='atm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.ATM'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Long.Bank'),
        ),
        migrations.DeleteModel(
            name='ATM',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='HistoryMoney',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
