# Generated by Django 3.0.1 on 2019-12-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0002_auto_20191223_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='hometown',
            new_name='address',
        ),
    ]
