# Generated by Django 3.0.1 on 2019-12-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0003_auto_20191224_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('No', 'Unknown')], max_length=2),
        ),
    ]
