# Generated by Django 3.0.1 on 2019-12-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0004_auto_20191225_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
