# Generated by Django 3.0.1 on 2020-01-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0005_auto_20191229_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
