# Generated by Django 3.0 on 2020-01-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0005_auto_20191228_1640'),
        ('Hoang', '0005_auto_20191229_0335'),
    ]

    operations = [
    ]
