# Generated by Django 3.0.1 on 2020-01-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0006_auto_20200112_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='card_no',
            new_name='id_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='card_type',
            new_name='id_type',
        ),
    ]
