# Generated by Django 3.0 on 2020-01-13 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hoang', '0007_auto_20200112_0912'),
        ('Hoang', '0007_auto_20200110_1526'),
    ]

    operations = [
    ]
